version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: python run.py runserver  --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    links:
      - db